name: Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - run: npm install --no-save express koa
      - run: npm ci
      - run: npm run check
      - run: npm test -- --collectCoverage
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/

  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ["18", "20", "latest"]
        deps:
          - express@4.18.x
          - express@4.17.x
          - koa@2.14.x
          - koa@2.13.x
          - "@nestjs/core@10.2.x @nestjs/common@10.2.x @nestjs/platform-express@10.2.x @nestjs/testing@10.2.x"
          - "@nestjs/core@9.4.x @nestjs/common@9.4.x @nestjs/platform-express@9.4.x @nestjs/testing@9.4.x"
          - "@nestjs/core@8.4.x @nestjs/common@8.4.x @nestjs/platform-express@8.4.x @nestjs/testing@8.4.x"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "${{ matrix.node }}"
          cache: npm
      - run: npm ci
      - run: npm install --no-save ${{ matrix.deps }}
      - run: npm test -- tests/express
        if: contains(matrix.deps, 'express')
      - run: npm test -- tests/koa
        if: contains(matrix.deps, 'koa')
      - run: npm test -- tests/nestjs
        if: contains(matrix.deps, 'nestjs')
